# NOTE: JSONが不自然な位置で改行される場合は、コメントアウトを意図的に追加する
trailingComma: all
overrides:
  - files:
      - "*.md"
    options:
      parser: markdown-nocjsp
  - files:
      - "*.mdx"
    options:
      parser: mdx-nocjsp
