version: "3.7"

services:

  www:
    container_name: tech-notebook-www
    hostname: tech-notebook-www
    build:
      dockerfile: ./infra/docker/www/Dockerfile
      target: develop
      context: .
    image: tech-notebook-www:latest
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/tech-notebook/public
    working_dir: /var/www/tech-notebook/public
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    networks:
      - default
      
  builder:
    container_name: tech-notebook-builder
    hostname: tech-notebook-builder
    build:
      dockerfile: ./infra/docker/builder/Dockerfile
      target: develop
      context: .
    image: tech-notebook-builder:latest
    tty: true
    volumes:
      - ./public:/var/www/tech-notebook/public
    working_dir: /var/www/tech-notebook/public
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    depends_on:
      - www
    networks:
      - default