# バージョン
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.11.0
  aws-ecs: circleci/aws-ecs@1.2.0
  slack: circleci/slack@3.4.2

commands:
  # checkoutに日本語対応化
  setup-git-config:
    steps:
      - run:
          name: Setup git config
          command: |
            git config --global core.quotepath false
            
  # 各イメージをDockerHubにプッシュ
  push-images:
    parameters:
      container-name:
        type: string
    steps:
      - setup-git-config
      # ソースコードを，/root/project(=tech-notebook) に配置# ソースコードを，/root/project(=tech-notebook) に配置
      - checkout
      - run:
          name: Build << parameters.container-name >>
          command: |
            docker build -f ./infra/docker/<< parameters.container-name >>/Dockerfile --target production -t ${DOCKER_USER}/${APP_NAME}-<< parameters.container-name >> .
      - run:
          name: Login to docker hub
          command: |
            echo ${DOCKER_PASS} |
            docker login -u ${DOCKER_USER} --password-stdin
      - run:
          name: Push << parameters.container-name >>
          command: |
            docker push ${DOCKER_USER}/${APP_NAME}-<< parameters.container-name >>:${DOCKER_VERSION}
      
  # ソースコードをワークスペースに保存
  persist-deploy-source:
    steps:
      - run:
          name: Make dir & Copy source to workspace
          command: |
            mkdir -p ./workspace/public/build
            cp -Rp ./public/build/* ./workspace/public/build
      - persist_to_workspace:
          root: ./workspace
          paths:
            # Rootをカレントとした時の相対ディレクトリ
            - ./public/build

  # Slackに失敗を通知する
  notify-failure-to-slack:
    parameters:
      message:
        type: string
        default: ${CIRCLE_JOB}
    steps:
      - slack/status:
          fail_only: true
          # メッセージ
          failure_message: "<< parameters.message >>に失敗しました:cry:"

# ジョブの設定
jobs:
  push-images-builder:
    # ホスト側環境の設定
    machine: true
    steps:
      - push-images:
          container-name: "builder"
          
  push-images-www:
    # ホスト側環境の設定
    machine: true
    steps:
      - push-images:
          container-name: "www"
        
  make-deploy-source:
    # ホスト側環境の設定
    docker:
      - image: ${DOCKER_USER}/${APP_NAME}-builder:${DOCKER_VERSION}
    steps:
      - setup-git-config
      # ソースコードを，/root/project(=tech-notebook) に配置
      - checkout
      - run:
          # READMEをサイト紹介ページとして利用
          name: Copy README.md
          command: |
            cp README.md ./public/source/about_this_site.md
      - run:
          # 本番環境にデプロイされるpublicディレクトリに移動
          # デプロイ用のHtmlを生成
          name: Make html
          command: |
            cd ./public
            make html

# 実行の順番を定義
workflows:
  version: 2.1
  build-push:
    jobs:
      # Deploy Image To Docker Hub
      - push-images-builder:
          post-steps:
            - notify-failure-to-slack
          filters:
            branches:
              only:
                # NOTE: productionブランチのみ起動
                - production
      # Deploy Image To Docker Hub
      - push-images-www:
          post-steps:
            - notify-failure-to-slack
          filters:
            branches:
              only:
                # NOTE: productionブランチのみ起動
                - production
      # Make Deploy Source
      - make-deploy-source:
          requires:
            - push-images-builder
            - push-images-www
          post-steps:
            - persist-deploy-source
            - notify-failure-to-slack
      # Deploy Production Image To ECR www -- Fix: env_var_name型設定項目は，${}をつけずに環境変数を出力
      - aws-ecr/build-and-push-image:
          requires:
            - make-deploy-source
          post-steps:
            - notify-failure-to-slack
          name: build-and-push-image-www
          path: ./infra/docker/www/Dockerfile
          dockerfile: Dockerfile
          extra-build-args: --target production
          repo: "${APP_NAME}-www"
          create-repo: true
          tag: ${CIRCLE_SHA1}
          attach-workspace: true
          workspace-root: ./workspace
      # Deploy Service To ECS www
      - aws-ecs/deploy-service-update:
          requires:
            - build-and-push-image-www
          post-steps:
            - notify-failure-to-slack
          name: deploy-service-update-www
          family: "${APP_NAME}-ecs-task-definition"
          cluster-name: "${APP_NAME}-ecs-cluster"
          service-name: "${APP_NAME}-ecs-service"
          deployment-controller: CODE_DEPLOY
          codedeploy-application-name: ${APP_NAME}
          codedeploy-deployment-group-name: "${APP_NAME}-deployment-group"
          codedeploy-load-balanced-container-name: www-container
          codedeploy-load-balanced-container-port: 80
          container-image-name-updates: "container=www-container,tag=${CIRCLE_SHA1}"