name: build_deploy

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config --local user.email "hasegawafeedshop@gmail.com"
          git config --local user.name "github-actions"
          git config pull.rebase false
      - name: Pip install
        uses: ./.github/workflows/composite/pip-install
      - name: Deploy MkDocs
        run: |
          mkdocs gh-deploy --force
