name: build_deploy

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config --local user.email "hasegawafeedshop@gmail.com"
          git config --local user.name "github-actions"
          git config pull.rebase false
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Pip install
        run: |
          pip3 install -r requirements.txt
      - name: Deploy MkDocs
        run: |
          mkdocs gh-deploy --force
