name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup git
        run: |
          git config --local user.email "hasegawafeedshop@gmail.com"
          git config --local user.name "github-actions"
          git config pull.rebase false
      - name: Pip install
        run: |
          pip3 install -r requirements.txt
      - name: Sed
        run: |
          find docs/md/* -name "*.md" -type f | xargs sed -i -e 's/，/、/g' -e 's/．/。/g'
      - name: Deploy MkDocs
        run: |
          mkdocs gh-deploy --force
